clients:
  - minioClientName: client1
    endpoint: 192.168.0.103:9001
    accessKeyID: minio
    secretAccessKey: minio123
    secure: false
    weight: 0.3
  - minioClientName: client2
    endpoint: 192.168.0.102:9001
    accessKeyID: minio
    secretAccessKey: minio123
    secure: false
    weight: 0.7